version: '3.5'  # Asegúrate que coincida con la versión del principal

services:
  test:
    build:
      context: ..
      dockerfile: infra/Dockerfile.test

    # referencia al servicio del archivo principal
    depends_on:
      - standalone

    environment:
      - MILVUS_URI=http://standalone:19530

      - SKIP_MILVUS_TESTS=False
